// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v3.21.1
// source: internal/grpcserver/protoc/service.proto

package service

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetCustomerIDRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	WorkingSiteId int32 `protobuf:"varint,1,opt,name=working_site_id,json=workingSiteId,proto3" json:"working_site_id,omitempty"`
	WorkerSiteId  int32 `protobuf:"varint,2,opt,name=worker_site_id,json=workerSiteId,proto3" json:"worker_site_id,omitempty"`
}

func (x *GetCustomerIDRequest) Reset() {
	*x = GetCustomerIDRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_grpcserver_protoc_service_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetCustomerIDRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCustomerIDRequest) ProtoMessage() {}

func (x *GetCustomerIDRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_grpcserver_protoc_service_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCustomerIDRequest.ProtoReflect.Descriptor instead.
func (*GetCustomerIDRequest) Descriptor() ([]byte, []int) {
	return file_internal_grpcserver_protoc_service_proto_rawDescGZIP(), []int{0}
}

func (x *GetCustomerIDRequest) GetWorkingSiteId() int32 {
	if x != nil {
		return x.WorkingSiteId
	}
	return 0
}

func (x *GetCustomerIDRequest) GetWorkerSiteId() int32 {
	if x != nil {
		return x.WorkerSiteId
	}
	return 0
}

type GetCustomerIDResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id int32 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *GetCustomerIDResponse) Reset() {
	*x = GetCustomerIDResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_grpcserver_protoc_service_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetCustomerIDResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCustomerIDResponse) ProtoMessage() {}

func (x *GetCustomerIDResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_grpcserver_protoc_service_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCustomerIDResponse.ProtoReflect.Descriptor instead.
func (*GetCustomerIDResponse) Descriptor() ([]byte, []int) {
	return file_internal_grpcserver_protoc_service_proto_rawDescGZIP(), []int{1}
}

func (x *GetCustomerIDResponse) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type GetWorkerSiteIDRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CustomerId    int32 `protobuf:"varint,1,opt,name=customer_id,json=customerId,proto3" json:"customer_id,omitempty"`
	WorkingSiteId int32 `protobuf:"varint,2,opt,name=working_site_id,json=workingSiteId,proto3" json:"working_site_id,omitempty"`
}

func (x *GetWorkerSiteIDRequest) Reset() {
	*x = GetWorkerSiteIDRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_grpcserver_protoc_service_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetWorkerSiteIDRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetWorkerSiteIDRequest) ProtoMessage() {}

func (x *GetWorkerSiteIDRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_grpcserver_protoc_service_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetWorkerSiteIDRequest.ProtoReflect.Descriptor instead.
func (*GetWorkerSiteIDRequest) Descriptor() ([]byte, []int) {
	return file_internal_grpcserver_protoc_service_proto_rawDescGZIP(), []int{2}
}

func (x *GetWorkerSiteIDRequest) GetCustomerId() int32 {
	if x != nil {
		return x.CustomerId
	}
	return 0
}

func (x *GetWorkerSiteIDRequest) GetWorkingSiteId() int32 {
	if x != nil {
		return x.WorkingSiteId
	}
	return 0
}

type GetWorkerSiteIDResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	WorkerSiteId int32 `protobuf:"varint,1,opt,name=worker_site_id,json=workerSiteId,proto3" json:"worker_site_id,omitempty"`
}

func (x *GetWorkerSiteIDResponse) Reset() {
	*x = GetWorkerSiteIDResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_grpcserver_protoc_service_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetWorkerSiteIDResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetWorkerSiteIDResponse) ProtoMessage() {}

func (x *GetWorkerSiteIDResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_grpcserver_protoc_service_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetWorkerSiteIDResponse.ProtoReflect.Descriptor instead.
func (*GetWorkerSiteIDResponse) Descriptor() ([]byte, []int) {
	return file_internal_grpcserver_protoc_service_proto_rawDescGZIP(), []int{3}
}

func (x *GetWorkerSiteIDResponse) GetWorkerSiteId() int32 {
	if x != nil {
		return x.WorkerSiteId
	}
	return 0
}

var File_internal_grpcserver_protoc_service_proto protoreflect.FileDescriptor

var file_internal_grpcserver_protoc_service_proto_rawDesc = []byte{
	0x0a, 0x28, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2f, 0x67, 0x72, 0x70, 0x63, 0x73,
	0x65, 0x72, 0x76, 0x65, 0x72, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x2f, 0x73, 0x65, 0x72,
	0x76, 0x69, 0x63, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x07, 0x73, 0x65, 0x72, 0x76,
	0x69, 0x63, 0x65, 0x22, 0x64, 0x0a, 0x14, 0x47, 0x65, 0x74, 0x43, 0x75, 0x73, 0x74, 0x6f, 0x6d,
	0x65, 0x72, 0x49, 0x44, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x26, 0x0a, 0x0f, 0x77,
	0x6f, 0x72, 0x6b, 0x69, 0x6e, 0x67, 0x5f, 0x73, 0x69, 0x74, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x0d, 0x77, 0x6f, 0x72, 0x6b, 0x69, 0x6e, 0x67, 0x53, 0x69, 0x74,
	0x65, 0x49, 0x64, 0x12, 0x24, 0x0a, 0x0e, 0x77, 0x6f, 0x72, 0x6b, 0x65, 0x72, 0x5f, 0x73, 0x69,
	0x74, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0c, 0x77, 0x6f, 0x72,
	0x6b, 0x65, 0x72, 0x53, 0x69, 0x74, 0x65, 0x49, 0x64, 0x22, 0x27, 0x0a, 0x15, 0x47, 0x65, 0x74,
	0x43, 0x75, 0x73, 0x74, 0x6f, 0x6d, 0x65, 0x72, 0x49, 0x44, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x02,
	0x69, 0x64, 0x22, 0x61, 0x0a, 0x16, 0x47, 0x65, 0x74, 0x57, 0x6f, 0x72, 0x6b, 0x65, 0x72, 0x53,
	0x69, 0x74, 0x65, 0x49, 0x44, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1f, 0x0a, 0x0b,
	0x63, 0x75, 0x73, 0x74, 0x6f, 0x6d, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x0a, 0x63, 0x75, 0x73, 0x74, 0x6f, 0x6d, 0x65, 0x72, 0x49, 0x64, 0x12, 0x26, 0x0a,
	0x0f, 0x77, 0x6f, 0x72, 0x6b, 0x69, 0x6e, 0x67, 0x5f, 0x73, 0x69, 0x74, 0x65, 0x5f, 0x69, 0x64,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0d, 0x77, 0x6f, 0x72, 0x6b, 0x69, 0x6e, 0x67, 0x53,
	0x69, 0x74, 0x65, 0x49, 0x64, 0x22, 0x3f, 0x0a, 0x17, 0x47, 0x65, 0x74, 0x57, 0x6f, 0x72, 0x6b,
	0x65, 0x72, 0x53, 0x69, 0x74, 0x65, 0x49, 0x44, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x24, 0x0a, 0x0e, 0x77, 0x6f, 0x72, 0x6b, 0x65, 0x72, 0x5f, 0x73, 0x69, 0x74, 0x65, 0x5f,
	0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0c, 0x77, 0x6f, 0x72, 0x6b, 0x65, 0x72,
	0x53, 0x69, 0x74, 0x65, 0x49, 0x64, 0x32, 0xb0, 0x01, 0x0a, 0x08, 0x43, 0x75, 0x73, 0x74, 0x6f,
	0x6d, 0x65, 0x72, 0x12, 0x4e, 0x0a, 0x0d, 0x47, 0x65, 0x74, 0x43, 0x75, 0x73, 0x74, 0x6f, 0x6d,
	0x65, 0x72, 0x49, 0x44, 0x12, 0x1d, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x47,
	0x65, 0x74, 0x43, 0x75, 0x73, 0x74, 0x6f, 0x6d, 0x65, 0x72, 0x49, 0x44, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x1a, 0x1e, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x47, 0x65,
	0x74, 0x43, 0x75, 0x73, 0x74, 0x6f, 0x6d, 0x65, 0x72, 0x49, 0x44, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x54, 0x0a, 0x0f, 0x47, 0x65, 0x74, 0x57, 0x6f, 0x72, 0x6b, 0x65, 0x72,
	0x53, 0x69, 0x74, 0x65, 0x49, 0x44, 0x12, 0x1f, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65,
	0x2e, 0x47, 0x65, 0x74, 0x57, 0x6f, 0x72, 0x6b, 0x65, 0x72, 0x53, 0x69, 0x74, 0x65, 0x49, 0x44,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x20, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63,
	0x65, 0x2e, 0x47, 0x65, 0x74, 0x57, 0x6f, 0x72, 0x6b, 0x65, 0x72, 0x53, 0x69, 0x74, 0x65, 0x49,
	0x44, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x24, 0x5a, 0x22, 0x69, 0x6e, 0x74,
	0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2f, 0x67, 0x72, 0x70, 0x63, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72,
	0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x2f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_internal_grpcserver_protoc_service_proto_rawDescOnce sync.Once
	file_internal_grpcserver_protoc_service_proto_rawDescData = file_internal_grpcserver_protoc_service_proto_rawDesc
)

func file_internal_grpcserver_protoc_service_proto_rawDescGZIP() []byte {
	file_internal_grpcserver_protoc_service_proto_rawDescOnce.Do(func() {
		file_internal_grpcserver_protoc_service_proto_rawDescData = protoimpl.X.CompressGZIP(file_internal_grpcserver_protoc_service_proto_rawDescData)
	})
	return file_internal_grpcserver_protoc_service_proto_rawDescData
}

var file_internal_grpcserver_protoc_service_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_internal_grpcserver_protoc_service_proto_goTypes = []interface{}{
	(*GetCustomerIDRequest)(nil),    // 0: service.GetCustomerIDRequest
	(*GetCustomerIDResponse)(nil),   // 1: service.GetCustomerIDResponse
	(*GetWorkerSiteIDRequest)(nil),  // 2: service.GetWorkerSiteIDRequest
	(*GetWorkerSiteIDResponse)(nil), // 3: service.GetWorkerSiteIDResponse
}
var file_internal_grpcserver_protoc_service_proto_depIdxs = []int32{
	0, // 0: service.Customer.GetCustomerID:input_type -> service.GetCustomerIDRequest
	2, // 1: service.Customer.GetWorkerSiteID:input_type -> service.GetWorkerSiteIDRequest
	1, // 2: service.Customer.GetCustomerID:output_type -> service.GetCustomerIDResponse
	3, // 3: service.Customer.GetWorkerSiteID:output_type -> service.GetWorkerSiteIDResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_internal_grpcserver_protoc_service_proto_init() }
func file_internal_grpcserver_protoc_service_proto_init() {
	if File_internal_grpcserver_protoc_service_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_internal_grpcserver_protoc_service_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetCustomerIDRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_grpcserver_protoc_service_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetCustomerIDResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_grpcserver_protoc_service_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetWorkerSiteIDRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_grpcserver_protoc_service_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetWorkerSiteIDResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_internal_grpcserver_protoc_service_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_internal_grpcserver_protoc_service_proto_goTypes,
		DependencyIndexes: file_internal_grpcserver_protoc_service_proto_depIdxs,
		MessageInfos:      file_internal_grpcserver_protoc_service_proto_msgTypes,
	}.Build()
	File_internal_grpcserver_protoc_service_proto = out.File
	file_internal_grpcserver_protoc_service_proto_rawDesc = nil
	file_internal_grpcserver_protoc_service_proto_goTypes = nil
	file_internal_grpcserver_protoc_service_proto_depIdxs = nil
}
