basePath: /
definitions:
  http_transport.Response:
    properties:
      code:
        type: integer
      data: {}
      error_code:
        type: string
      error_message:
        type: string
      message:
        type: string
      status:
        type: string
    type: object
host: localhost:8000
info:
  contact: {}
paths:
  /grab-electric/orders/customer/{customer_code}:
    get:
      operationId: get-orders
      parameters:
      - description: todo ID
        in: path
        name: customer_code
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/http_transport.Response'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/http_transport.Response'
      summary: get a list order of customer
swagger: "2.0"
